name: Update Codolio DSA Stats

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dsa-stats-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Codolio Stats SVG
        run: |
          HTTP_STATUS=$(curl -o dsa-stats.svg -w "%{http_code}" https://dsastats.vercel.app/api/codolio/ImagineAnsh)
          echo "HTTP Status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Failed to fetch SVG. Status: $HTTP_STATUS"
            cat dsa-stats.svg
            exit 1
          fi

      - name: Commit and Push SVG to main
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dsa-stats.svg
          git diff --cached --quiet || git commit -m "Update Codolio stats $(date +'%Y-%m-%d')"
          git push origin main
